# Generated by Django 3.1.5 on 2024-02-14 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='visit_count',
        ),
        migrations.AddField(
            model_name='idea',
            name='new_date_field',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
