# Generated by Django 3.1.5 on 2024-02-05 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='email',
            new_name='Mail',
        ),
        migrations.AddField(
            model_name='author',
            name='designation',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
