# Generated by Django 3.1.5 on 2024-02-05 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20240205_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='Mail',
        ),
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='author',
            name='email_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Email as Text'),
        ),
    ]
